{{- range $name, $pages := .Values.maintenance.customPages }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maintenance-page-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "maintenance-operator.labels" $ | nindent 4 }}
    maintenance-operator.kahf.io/custom-page: "true"
data:
  {{- if $pages.htmlBase64 }}
  page.html: |
{{ $pages.htmlBase64 | b64dec | indent 4 }}
  {{- else }}
  page.html: |
{{ $.Values.maintenance.defaultPage.htmlBase64 | b64dec | indent 4 }}
  {{- end }}
  {{- if $pages.json }}
  page.json: |
{{ $pages.json | indent 4 }}
  {{- else }}
  page.json: |
{{ $.Values.maintenance.defaultPage.json | indent 4 }}
  {{- end }}
  {{- if $pages.xml }}
  page.xml: |
{{ $pages.xml | indent 4 }}
  {{- else }}
  page.xml: |
{{ $.Values.maintenance.defaultPage.xml | indent 4 }}
  {{- end }}
{{- end }}
