apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "maintenance-operator.fullname" . }}-default-pages
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maintenance-operator.labels" . | nindent 4 }}
data:
  page.html: |
{{ .Values.maintenance.defaultPage.htmlBase64 | b64dec | indent 4 }}
  page.json: |
{{ .Values.maintenance.defaultPage.json | indent 4 }}
  page.xml: |
{{ .Values.maintenance.defaultPage.xml | indent 4 }}
