apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maintenance-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maintenance-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "maintenance-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-default-pages.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "maintenance-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "maintenance-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        # Operator controller
        - name: operator
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["kopf", "run", "/app/maintenance_operator.py", "--verbose"]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MAINTENANCE_ANNOTATION
              value: {{ .Values.operator.maintenanceAnnotation | quote }}
            - name: MAINTENANCE_ANNOTATION_VALUE
              value: {{ .Values.operator.maintenanceAnnotationValue | quote }}
            - name: BACKUP_ANNOTATION
              value: {{ .Values.operator.backupAnnotation | quote }}
            - name: CUSTOM_PAGE_ANNOTATION
              value: {{ .Values.operator.customPageAnnotation | quote }}
            - name: BACKUP_CONFIGMAP_PREFIX
              value: {{ .Values.operator.backupConfigMapPrefix | quote }}
            - name: MAINTENANCE_CONFIGMAP_NAME
              value: {{ include "maintenance-operator.fullname" . }}-default-pages
            - name: MAINTENANCE_SERVICE_PORT
              value: "80"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir: {}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
